{% set name = "kinbot" %}
{% set version = "2.2.4" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kinbot-{{ version }}.tar.gz
  sha256: 5e72cd0696c9bdc961cdacbba44b9ec2e80d2831c0ba030173c214b80ff7a6db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - kinbot = kinbot.kb:main
    - pes = kinbot.pes:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.17.0
    - ase >=3.19,<3.23.0
    - networkx
    - rmsd >=1.5.1
    - sella

test:
  imports:
    - kinbot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/zadorlab/KinBot
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Automated reaction pathway search for gas-phase molecules.

  description: |
    KinBot is an automated gas-phase kinetics workflow code that drives
    electronic structure calculations on a chemical PES and characterizes
    the chemically relevant stationary points to finally create a complete
    master equation formulation of the chemical kinetic system.
  doc_url: https://github.com/zadorlab/KinBot/wiki
  dev_url: https://github.com/zadorlab/KinBot

extra:
  recipe-maintainers:
    - juditzador
